version: '2'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    image: tasnimab1/achat:1-0
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on: [db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  db_data: