version: '3.8'
# definir container
services:

  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    volumes:
      - db_data:/var/lib/mysql
  # spring app
  backend:
    image: mayssa1999/achat:1-0
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/achatdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

  frontend:
   image : mayssa1999/crudtutofront:v1
   restart: unless-stopped
   ports:
     - "80:80"

volumes:
  db_data:
