version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
    networks:
        - mynetwork

  backend:
    image: tasnimab1/achat:1-0
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  db_data: