version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      my-custom-network:
        ipv4_address: 172.19.0.4

  achat-backend:
    image: abirmekki/achat:1-2
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      my-custom-network:
        ipv4_address: 172.19.0.5

  achat-front:
    image: abirmekki/front:1-1
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      my-custom-network:
        ipv4_address: 172.19.0.6

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      my-custom-network:
        ipv4_address: 172.19.0.7

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      my-custom-network:
        ipv4_address: 172.19.0.8


volumes:
  db:

networks:
  my-custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
