version: '3.8'

services:
  # MySQL database service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      my-custom-network:
        ipv4_address: 172.19.0.4

  # Spring Boot application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      my-custom-network:
        ipv4_address: 172.19.0.5

  # Frontend application service
  front:
    image: yasminerebai/achat:1.0-Front
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      my-custom-network:
        ipv4_address: 172.19.0.6

volumes:
  mysql-data:
networks:
  my-custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16